uploads = []
generated = []

[[outputs]]
id = "V4BhHUipMjujlVtdqBD7G"
uri = "file://public/ticket-preview.jpg"
type = "image"
title = "Ticket resumen tótem – con Desde/Hasta corregido"

[[outputs]]
id = "q6CUWaNCXA51gTQ8QCOGZ"
uri = "file://exports/ticket-rosa.svg"
type = "image"
title = "Vale impreso - Rosa Maria Quillas Almonacid"

[[outputs]]
id = "9NzuYURDUXQd-hmPvNoSH"
uri = "file://exports/ticket-calderon.svg"
type = "image"
title = "Vale impreso - Michael Calderón (CASINO BAUMAX)"

[[outputs]]
id = "3GCb9DhhBZuswouyhB85W"
uri = "file://exports/resumen-baumax.svg"
type = "image"
title = "Previsualización - Resumen tótem CASINO BAUMAX (27/05/2026)"

[[outputs]]
id = "21iS-5bzaDIj5UJkkqN7T"
uri = "file://documentos/WebMakerChile - Hosting y Mantencion - BuenaMezcla.pdf"
type = "pdf"
title = "Hosting y Mantención - BuenaMezcla (actualizado)"
